"""Debian/Ubuntu network interface configuration (/etc/network/interfaces)."""

from io import StringIO

from pyinfra.api.operation import add_op
from pyinfra.operations import files, server


def add_debian_network_ops(state, hosts, config, target_hosts=None, task="all"):
    """Configure Debian/Ubuntu network interfaces via /etc/network/interfaces.

    Manages static IP addresses, gateways, DNS, bridge configurations, "manual"
    stub interfaces (e.g. physical NICs enslaved to a bridge that carry no
    address of their own), and an optional trailing `source` directive (e.g.
    for Proxmox-style `/etc/network/interfaces.d/*` drop-ins).

    Args:
        state: pyinfra State object
        hosts: Inventory object
        config: dict mapping hostname → network config
            {
                "pve.paris": {
                    "interfaces": [
                        {
                            "name": "vmbr0",
                            "type": "inet",  # address family: inet or inet6 (default inet)
                            "method": "static",  # "static" (default) or "manual"
                            "auto": True,  # emit "auto <name>" before the iface line (default True)
                            "address": "10.40.0.145",
                            "netmask": "255.255.255.0",
                            "gateway": "10.40.0.253",
                            "dns_nameservers": ["10.40.0.253", "8.8.8.8"],
                            "dns_search": "lan london newyork",
                            "ports": ["nic0"],  # For bridges
                        },
                        {
                            # A stub interface enslaved to the bridge above - no
                            # address/gateway/dns, and not auto-started itself.
                            "name": "nic0",
                            "method": "manual",
                            "auto": False,
                        },
                    ],
                    # Optional: emit "source <pattern>" line(s) after all interfaces
                    "sources": ["/etc/network/interfaces.d/*"],
                }
            }
        target_hosts: list of Host objects (default: all)
        task: "debian_network" or "all"
    """
    targets = target_hosts if target_hosts else list(hosts)

    for host in targets:
        if host.name not in config:
            continue

        net_config = config[host.name]

        # Build /etc/network/interfaces from config
        interfaces_content = _build_interfaces_file(net_config)

        # Backup existing configuration
        add_op(
            state,
            server.shell,
            name=f"Backup /etc/network/interfaces on {host.name}",
            commands=[
                "test -f /etc/network/interfaces && cp /etc/network/interfaces /etc/network/interfaces.bak || true"
            ],
            host=host,
        )

        # Deploy new configuration
        add_op(
            state,
            files.put,
            name=f"Deploy /etc/network/interfaces on {host.name}",
            src=StringIO(interfaces_content),
            dest="/etc/network/interfaces",
            mode="0644",
            host=host,
        )

        # Restart networking service
        add_op(
            state,
            server.shell,
            name=f"Restart networking on {host.name}",
            commands=["systemctl restart networking || /etc/init.d/networking restart"],
            host=host,
        )

        # Verify configuration applied
        add_op(
            state,
            server.shell,
            name=f"Verify network configuration on {host.name}",
            commands=["ip route | grep ^default"],
            host=host,
        )


def _build_interfaces_file(config):
    """Build /etc/network/interfaces content from config dict.

    Args:
        config: dict with 'interfaces' list

    Returns:
        str: Content for /etc/network/interfaces file
    """
    lines = [
        "# Generated by flamelet - Do not edit manually\n",
        "# See <tenant>/vars/hosts/<hostname>.py\n",
        "\n",
    ]

    # Loopback interface
    lines.append("auto lo\n")
    lines.append("iface lo inet loopback\n")
    lines.append("\n")

    # Physical and virtual interfaces
    for iface in config.get("interfaces", []):
        name = iface.get("name")
        if not name:
            continue

        # NOTE: "type" is the ADDRESS FAMILY (inet/inet6) that goes between the
        # interface name and "static" in the iface line below, e.g.
        # "iface eth0 inet static" - it is NOT the method or interface role.
        # Bridges are already distinguished by the presence of "ports" below,
        # not by this field. Previously several host configs set "type" to
        # "static" or "bridge" (the role, not the family), which produced
        # invalid output like "iface eth0 static static" - always fall back to
        # "inet" for anything that isn't a recognized address family so a wrong
        # value in config data can't produce broken interfaces syntax.
        iface_type = iface.get("type", "inet")
        if iface_type not in ("inet", "inet6"):
            iface_type = "inet"

        # "manual" is for stub interfaces (e.g. physical NICs enslaved to a
        # bridge via that bridge's "ports") that carry no address/gateway/DNS
        # of their own - just declared so ifupdown/the bridge knows about them.
        method = iface.get("method", "static")
        if method not in ("static", "manual"):
            method = "static"

        auto = iface.get("auto", True)
        address = iface.get("address")
        netmask = iface.get("netmask")
        gateway = iface.get("gateway")
        ports = iface.get("ports", [])
        dns_nameservers = iface.get("dns_nameservers", [])
        dns_search = iface.get("dns_search")

        # Interface declaration
        if auto:
            lines.append(f"auto {name}\n")
        lines.append(f"iface {name} {iface_type} {method}\n")

        if method == "manual":
            # Manual interfaces carry no address/gateway/dns/bridge config
            lines.append("\n")
            continue

        # Address configuration
        if address and netmask:
            lines.append(f"    address {address}\n")
            lines.append(f"    netmask {netmask}\n")
        elif address:
            # Support CIDR notation (e.g., 10.40.0.145/24)
            lines.append(f"    address {address}\n")

        # Gateway
        if gateway:
            lines.append(f"    gateway {gateway}\n")

        # Bridge configuration (if applicable)
        if ports:
            lines.append(f"    bridge-ports {' '.join(ports)}\n")
            lines.append("    bridge-stp off\n")
            lines.append("    bridge-fd 0\n")

        # DNS configuration
        if dns_nameservers:
            lines.append(f"    dns-nameservers {' '.join(dns_nameservers)}\n")

        if dns_search:
            if isinstance(dns_search, list):
                dns_search = " ".join(dns_search)
            lines.append(f"    dns-search {dns_search}\n")

        lines.append("\n")

    # Optional trailing "source" directive(s), e.g. for Proxmox-style
    # /etc/network/interfaces.d/* drop-ins
    sources = config.get("sources", [])
    if isinstance(sources, str):
        sources = [sources]
    for source_pattern in sources:
        lines.append(f"source {source_pattern}\n")

    return "".join(lines)
