"""Debian/Ubuntu network interface configuration (/etc/network/interfaces)."""

from io import StringIO
from pyinfra.api.operation import add_op
from pyinfra.operations import files, server


def add_debian_network_ops(state, hosts, config, target_hosts=None, task="all"):
    """Configure Debian/Ubuntu network interfaces via /etc/network/interfaces.

    Manages static IP addresses, gateways, DNS, and bridge configurations.

    Args:
        state: pyinfra State object
        hosts: Inventory object
        config: dict mapping hostname → network config
            {
                "pve.work": {
                    "interfaces": [
                        {
                            "name": "vmbr0",
                            "type": "bridge",
                            "address": "192.168.80.145",
                            "netmask": "255.255.255.0",
                            "gateway": "192.168.80.253",
                            "dns_nameservers": ["192.168.80.253", "8.8.8.8"],
                            "dns_search": "lan work home baar",
                            "ports": ["nic0"],  # For bridges
                        }
                    ]
                }
            }
        target_hosts: list of Host objects (default: all)
        task: "debian_network" or "all"
    """
    targets = target_hosts if target_hosts else list(hosts)

    for host in targets:
        if host.name not in config:
            continue

        net_config = config[host.name]

        # Build /etc/network/interfaces from config
        interfaces_content = _build_interfaces_file(net_config)

        # Backup existing configuration
        add_op(
            state,
            server.shell,
            name=f"Backup /etc/network/interfaces on {host.name}",
            commands=["test -f /etc/network/interfaces && cp /etc/network/interfaces /etc/network/interfaces.bak || true"],
            host=host,
        )

        # Deploy new configuration
        add_op(
            state,
            files.put,
            name=f"Deploy /etc/network/interfaces on {host.name}",
            src=StringIO(interfaces_content),
            dest="/etc/network/interfaces",
            mode="0644",
            host=host,
        )

        # Restart networking service
        add_op(
            state,
            server.shell,
            name=f"Restart networking on {host.name}",
            commands=["systemctl restart networking || /etc/init.d/networking restart"],
            host=host,
        )

        # Verify configuration applied
        add_op(
            state,
            server.shell,
            name=f"Verify network configuration on {host.name}",
            commands=["ip route | grep ^default"],
            host=host,
        )


def _build_interfaces_file(config):
    """Build /etc/network/interfaces content from config dict.

    Args:
        config: dict with 'interfaces' list

    Returns:
        str: Content for /etc/network/interfaces file
    """
    lines = [
        "# Generated by flamelet - Do not edit manually\n",
        "# See /home/syseng/.config/flamelet/tenants/flamelet-home/vars/hosts/pve_work.py\n",
        "\n",
    ]

    # Loopback interface
    lines.append("auto lo\n")
    lines.append("iface lo inet loopback\n")
    lines.append("\n")

    # Physical and virtual interfaces
    for iface in config.get("interfaces", []):
        name = iface.get("name")
        if not name:
            continue

        iface_type = iface.get("type", "inet")
        address = iface.get("address")
        netmask = iface.get("netmask")
        gateway = iface.get("gateway")
        ports = iface.get("ports", [])
        dns_nameservers = iface.get("dns_nameservers", [])
        dns_search = iface.get("dns_search")

        # Interface declaration
        lines.append(f"auto {name}\n")
        lines.append(f"iface {name} {iface_type} static\n")

        # Address configuration
        if address and netmask:
            lines.append(f"    address {address}\n")
            lines.append(f"    netmask {netmask}\n")
        elif address:
            # Support CIDR notation (e.g., 192.168.80.145/24)
            lines.append(f"    address {address}\n")

        # Gateway
        if gateway:
            lines.append(f"    gateway {gateway}\n")

        # Bridge configuration (if applicable)
        if ports:
            lines.append(f"    bridge-ports {' '.join(ports)}\n")
            lines.append("    bridge-stp off\n")
            lines.append("    bridge-fd 0\n")

        # DNS configuration
        if dns_nameservers:
            lines.append(f"    dns-nameservers {' '.join(dns_nameservers)}\n")

        if dns_search:
            if isinstance(dns_search, list):
                dns_search = " ".join(dns_search)
            lines.append(f"    dns-search {dns_search}\n")

        lines.append("\n")

    return "".join(lines)
