"""Gateway Netbird routing configuration for LXC containers.

Deploys nftables NAT and policy routing rules to enable Netbird subnet routing
for non-Netbird LAN clients (DHCP clients, VMs) on gateway containers.

Without these rules, LAN clients cannot reach remote subnets via the gateway's
Netbird connection - they send packets with unroutable local source IPs.

Critical for: gateway.newyork, gateway.madrid, gateway.london, gateway.tokyo
during Phase 2 trial and eventual Tailscale retirement.
"""

from pyinfra.api.operation import add_op
from pyinfra.facts.server import Kernel
from pyinfra.operations import server


def add_gateway_netbird_routing_ops(state, hosts, config, target_hosts=None, task="all"):
    """Configure gateway Netbird routing on Linux LXC containers.

    Args:
        state: pyinfra State object
        hosts: Inventory object
        config: dict mapping hostname → routing config
            {
                "gateway.newyork": {
                    "local_subnet": "10.20.0.0/24",
                    "enable_watchdog": True,
                    "watchdog_interval": "*/5 * * * *",
                }
            }
        target_hosts: list of Host objects (default: all)
        task: "gateway-netbird-routing" or "all"
    """
    targets = target_hosts if target_hosts else list(hosts)

    for host in targets:
        if host.name not in config:
            continue

        os_key = host.get_fact(Kernel)
        routing_config = config[host.name]

        # Only deploy on Linux (nftables requirement)
        if os_key != "Linux":
            continue

        local_subnet = routing_config.get("local_subnet")
        enable_watchdog = routing_config.get("enable_watchdog", False)
        watchdog_interval = routing_config.get("watchdog_interval", "*/5 * * * *")

        if not local_subnet:
            raise ValueError(f"gateway_netbird_routing: {host.name} missing 'local_subnet'")

        _deploy_gateway_routing_script(state, host, local_subnet)
        _apply_routing_rules(state, host, local_subnet)

        if enable_watchdog:
            _deploy_watchdog_cron(state, host, watchdog_interval)


def _deploy_gateway_routing_script(state, host, local_subnet):
    """Deploy fix-netbird-route.sh script to gateway container."""

    # Generate script content with subnet interpolation
    script_content = f"""#!/bin/bash
# Fix Netbird routing for LAN clients on {host.name}
# Generated by flamelet gateway_netbird_routing operation
# Local subnet: {local_subnet}

# Policy routing: ensure packets destined for local subnet use main table
# This prevents Netbird from intercepting local-destined traffic
ip rule list | grep -q "to {local_subnet} lookup main" || \\
  ip rule add to {local_subnet} lookup main priority 100

# Create nftables table for custom NAT rules (idempotent)
nft list table ip custom-nat-nb >/dev/null 2>&1 || \\
  nft add table ip custom-nat-nb

# Create postrouting chain (idempotent)
nft list chain ip custom-nat-nb postrouting >/dev/null 2>&1 || \\
  nft add chain ip custom-nat-nb postrouting '{{ type nat hook postrouting priority 100 ; }}'

# Add masquerade rule for LAN clients exiting via Netbird (idempotent)
# This rewrites source IP from local subnet to gateway IP so remote peers can reply
nft list chain ip custom-nat-nb postrouting 2>/dev/null | \\
  grep -q 'oifname "wt0" ip saddr {local_subnet} masquerade' || \\
  nft add rule ip custom-nat-nb postrouting oifname "wt0" ip saddr {local_subnet} masquerade
"""

    heredoc_cmd = (
        'cat > /usr/local/sbin/fix-netbird-route.sh << \'SCRIPT_EOF\'\n'
        f'{script_content}\nSCRIPT_EOF'
    )

    add_op(
        state,
        server.shell,
        name=f"Deploy fix-netbird-route.sh on {host.name}",
        commands=[heredoc_cmd],
        host=host,
    )

    # Make executable
    add_op(
        state,
        server.shell,
        name=f"Make fix-netbird-route.sh executable on {host.name}",
        commands=["chmod 755 /usr/local/sbin/fix-netbird-route.sh"],
        host=host,
    )


def _apply_routing_rules(state, host, local_subnet):
    """Apply routing rules immediately on first deployment."""

    add_op(
        state,
        server.shell,
        name=f"Apply Netbird gateway routing on {host.name}",
        commands=["/usr/local/sbin/fix-netbird-route.sh"],
        host=host,
    )

    # Verify policy rule was added
    add_op(
        state,
        server.shell,
        name=f"Verify policy routing on {host.name}",
        commands=[f"ip rule list | grep '{local_subnet}'"],
        host=host,
    )

    # Verify nftables table and chain exist
    add_op(
        state,
        server.shell,
        name=f"Verify nftables rules on {host.name}",
        commands=[
            "nft list table ip custom-nat-nb",
            'nft list chain ip custom-nat-nb postrouting | grep masquerade',
        ],
        host=host,
    )


def _deploy_watchdog_cron(state, host, watchdog_interval):
    """Deploy cron job to re-apply routing rules periodically.

    This ensures routes survive Netbird restarts or manual rule deletion.
    """

    cron_content = f"""# Netbird gateway routing watchdog
# Automatically re-apply routing rules every {watchdog_interval}
{watchdog_interval} root /usr/local/sbin/fix-netbird-route.sh >> /var/log/fix-netbird-route.log 2>&1
"""

    heredoc_cmd = (
        'cat > /etc/cron.d/fix-netbird-route-watchdog << \'CRON_EOF\'\n'
        f'{cron_content}\nCRON_EOF'
    )

    add_op(
        state,
        server.shell,
        name=f"Deploy watchdog cron on {host.name}",
        commands=[heredoc_cmd],
        host=host,
    )

    # Verify cron was deployed
    add_op(
        state,
        server.shell,
        name=f"Verify watchdog cron on {host.name}",
        commands=["cat /etc/cron.d/fix-netbird-route-watchdog"],
        host=host,
    )
