"""Nginx HTTP/HTTPS reverse proxy and load balancer operations."""

from io import StringIO

from pyinfra.api.operation import add_op
from pyinfra.facts.server import Kernel
from pyinfra.operations import files, server


def add_nginx_ops(state, hosts, config, target_hosts=None, task="all"):
    """Deploy nginx reverse proxy with upstream and server blocks.

    Args:
        state: pyinfra State object
        hosts: Inventory object
        config: dict mapping hostname → {
            "upstreams": [
                {"name": "backend", "servers": ["10.0.0.1:8080", "10.0.0.2:8080"]},
            ],
            "servers": [
                {
                    "server_name": "example.com www.example.com",
                    "listen": [80, 443],
                    "ssl_cert": "/etc/ssl/certs/cert.pem",
                    "ssl_key": "/etc/ssl/private/key.pem",
                    "upstream": "backend",
                    "locations": [
                        {"path": "/", "proxy_pass": "http://backend"}
                    ],
                }
            ],
        }
        target_hosts: list of Host objects to deploy to (default: all)
        task: "nginx" or "all" (for compatibility)
    """
    targets = target_hosts if target_hosts else list(hosts)

    for host in targets:
        if host.name not in config:
            continue

        spec = config[host.name]
        os_key = host.get_fact(Kernel)

        # OS-aware paths
        if os_key == "FreeBSD":
            conf_dir = "/usr/local/etc/nginx"
            service_name = "nginx"
        elif os_key == "OpenBSD":
            conf_dir = "/etc/nginx"
            service_name = "nginx"
        else:  # Linux
            conf_dir = "/etc/nginx"
            service_name = "nginx"

        # Generate nginx.conf
        config_content = _generate_nginx_config(spec)

        # Deploy main config
        add_op(
            state,
            files.put,
            name=f"Deploy nginx config on {host.name}",
            src=StringIO(config_content),
            dest=f"{conf_dir}/nginx.conf",
            user="root",
            group="root",
            mode="0644",
            host=host,
        )

        # Validate configuration
        add_op(
            state,
            server.shell,
            name=f"Validate nginx config on {host.name}",
            commands=["nginx -t"],
            host=host,
        )

        # Enable and start nginx
        add_op(
            state,
            server.service,
            name=service_name,
            state="started",
            enabled=True,
            host=host,
        )

        # Reload nginx to apply changes
        add_op(
            state,
            server.shell,
            name=f"Reload nginx on {host.name}",
            commands=["nginx -s reload"],
            host=host,
        )


def _generate_nginx_config(spec):
    """Generate nginx.conf from configuration dict."""
    config_lines = [
        "# Generated by Flamelet",
        "user nginx;",
        "worker_processes auto;",
        "error_log /var/log/nginx/error.log warn;",
        "pid /var/run/nginx.pid;",
        "",
        "events {",
        "    worker_connections 1024;",
        "}",
        "",
        "http {",
        "    include /etc/nginx/mime.types;",
        "    default_type application/octet-stream;",
        "",
        "    log_format main '$remote_addr - $remote_user [$time_local] \"$request\" '",
        "                    '$status $body_bytes_sent \"$http_referer\" '",
        '                    \'"$http_user_agent" "$http_x_forwarded_for";',
        "",
        "    access_log /var/log/nginx/access.log main;",
        "",
        "    sendfile on;",
        "    tcp_nopush on;",
        "    tcp_nodelay on;",
        "    keepalive_timeout 65;",
        "    types_hash_max_size 2048;",
        "    client_max_body_size 100M;",
        "",
    ]

    # Add upstream blocks
    for upstream in spec.get("upstreams", []):
        config_lines.append(f"    upstream {upstream['name']} {{")
        for srv in upstream.get("servers", []):
            config_lines.append(f"        server {srv};")
        config_lines.append("    }")
        config_lines.append("")

    # Add server blocks
    for srv_block in spec.get("servers", []):
        config_lines.append("    server {")

        # Listen directives
        for port in srv_block.get("listen", [80]):
            if port == 443:
                config_lines.append(f"        listen {port} ssl http2;")
            else:
                config_lines.append(f"        listen {port};")

        # Server name
        config_lines.append(f"        server_name {srv_block.get('server_name', '_')};")

        # SSL directives
        if "ssl_cert" in srv_block:
            config_lines.append(f"        ssl_certificate {srv_block['ssl_cert']};")
        if "ssl_key" in srv_block:
            config_lines.append(f"        ssl_certificate_key {srv_block['ssl_key']};")

        # Location blocks
        for location in srv_block.get("locations", []):
            path = location.get("path", "/")
            config_lines.append(f"        location {path} {{")

            if "proxy_pass" in location:
                config_lines.append(f"            proxy_pass {location['proxy_pass']};")
                config_lines.append("            proxy_set_header Host $host;")
                config_lines.append("            proxy_set_header X-Real-IP $remote_addr;")
                config_lines.append(
                    "            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;"
                )
                config_lines.append("            proxy_set_header X-Forwarded-Proto $scheme;")

            if "root" in location:
                config_lines.append(f"            root {location['root']};")

            if "index" in location:
                config_lines.append(f"            index {location['index']};")

            config_lines.append("        }")

        config_lines.append("    }")
        config_lines.append("")

    config_lines.append("}")

    return "\n".join(config_lines)
