"""Prometheus monitoring server operations."""

from io import StringIO

from pyinfra.api.operation import add_op
from pyinfra.facts.server import Kernel
from pyinfra.operations import files, server


def add_prometheus_ops(state, hosts, config, target_hosts=None, task="all"):
    """Deploy Prometheus metrics server with scrape targets and alerts.

    Args:
        state: pyinfra State object
        hosts: Inventory object
        config: dict mapping hostname → {
            "listen_address": ":9090",
            "retention": "15d",
            "scrape_interval": "15s",
            "scrape_targets": [
                {"job_name": "node", "targets": ["localhost:9100"]},
                {"job_name": "docker", "targets": ["localhost:9323"]},
            ],
            "alert_rules": [
                {"alert": "HighCPU", "expr": "..."},
            ],
            "alert_manager": "alertmanager:9093",
        }
        target_hosts: list of Host objects to deploy to (default: all)
        task: "prometheus" or "all" (for compatibility)
    """
    targets = target_hosts if target_hosts else list(hosts)

    for host in targets:
        if host.name not in config:
            continue

        spec = config[host.name]
        os_key = host.get_fact(Kernel)

        # OS-aware paths
        if os_key == "FreeBSD":
            conf_dir = "/usr/local/etc/prometheus"
        elif os_key == "OpenBSD":
            conf_dir = "/etc/prometheus"
        else:  # Linux
            conf_dir = "/etc/prometheus"

        # Create config directory
        add_op(
            state,
            server.shell,
            name=f"Create Prometheus config directory on {host.name}",
            commands=[f"mkdir -p {conf_dir}"],
            host=host,
        )

        # Generate prometheus.yml
        prometheus_yaml = _generate_prometheus_yml(spec, conf_dir)

        add_op(
            state,
            files.put,
            name=f"Deploy prometheus.yml on {host.name}",
            src=StringIO(prometheus_yaml),
            dest=f"{conf_dir}/prometheus.yml",
            user="prometheus",
            group="prometheus",
            mode="0644",
            host=host,
        )

        # Generate alert rules if specified
        if spec.get("alert_rules"):
            alert_rules = _generate_alert_rules(spec["alert_rules"])
            add_op(
                state,
                files.put,
                name=f"Deploy Prometheus alert rules on {host.name}",
                src=StringIO(alert_rules),
                dest=f"{conf_dir}/alert.rules.yml",
                user="prometheus",
                group="prometheus",
                mode="0644",
                host=host,
            )

        # Install Prometheus (systemd service)
        add_op(
            state,
            server.shell,
            name=f"Install Prometheus on {host.name}",
            commands=[
                f"which prometheus || {_install_prometheus(os_key)}",
                _create_prometheus_user(os_key),
                f"chown -R prometheus:prometheus {conf_dir}",
            ],
            host=host,
        )

        # Enable and start Prometheus
        add_op(
            state,
            server.service,
            name="prometheus",
            state="started",
            enabled=True,
            host=host,
        )


def _generate_prometheus_yml(spec, conf_dir):
    """Generate prometheus.yml configuration."""
    yaml_lines = [
        "# Generated by Flamelet",
        "global:",
        f"  scrape_interval: {spec.get('scrape_interval', '15s')}",
        f"  evaluation_interval: {spec.get('evaluation_interval', '15s')}",
        "  external_labels:",
        "    instance: prometheus",
        "",
    ]

    # Alerting configuration
    if spec.get("alert_rules"):
        yaml_lines.extend(
            [
                "alerting:",
                "  alertmanagers:",
                "    - static_configs:",
                f"        - targets: ['{spec.get('alert_manager', 'localhost:9093')}']",
                "",
                "rule_files:",
                f"  - '{conf_dir}/alert.rules.yml'",
                "",
            ]
        )

    # Scrape targets
    yaml_lines.append("scrape_configs:")

    for target in spec.get("scrape_targets", []):
        job_name = target.get("job_name", "default")
        targets_list = target.get("targets", ["localhost:9090"])

        yaml_lines.extend(
            [
                f"  - job_name: '{job_name}'",
                "    static_configs:",
                "      - targets:",
            ]
        )

        for t in targets_list:
            yaml_lines.append(f"          - '{t}'")

        if "scrape_interval" in target:
            yaml_lines.append(f"    scrape_interval: {target['scrape_interval']}")

        yaml_lines.append("")

    return "\n".join(yaml_lines)


def _generate_alert_rules(alert_rules):
    """Generate Prometheus alert rules configuration."""
    yaml_lines = [
        "# Generated by Flamelet",
        "groups:",
        "  - name: alerts",
        "    interval: 1m",
        "    rules:",
    ]

    for rule in alert_rules:
        yaml_lines.extend(
            [
                f"      - alert: {rule['alert']}",
                f"        expr: {rule['expr']}",
                f"        for: {rule.get('for', '5m')}",
                "        labels:",
                f"          severity: {rule.get('severity', 'warning')}",
                "        annotations:",
                f'          summary: "{rule.get("summary", rule["alert"])}"',
                f'          description: "{rule.get("description", "")}"',
            ]
        )

    return "\n".join(yaml_lines)


def _install_prometheus(os_key):
    """Return OS-specific Prometheus install command."""
    if os_key == "FreeBSD":
        return "pkg install -y prometheus"
    elif os_key == "OpenBSD":
        return "pkg_add prometheus"
    else:  # Linux (Debian)
        return "apt-get update && apt-get install -y prometheus"


def _create_prometheus_user(os_key):
    """Return OS-specific Prometheus user creation command."""
    if os_key == "FreeBSD":
        return "pw useradd -n prometheus -s /usr/sbin/nologin -m -d /nonexistent 2>/dev/null || true"
    elif os_key == "OpenBSD":
        return "useradd -s /usr/sbin/nologin -d /var/empty -m prometheus 2>/dev/null || true"
    else:  # Linux
        return "useradd -s /sbin/nologin -M prometheus 2>/dev/null || true"
