"""Docker Container Registry operations."""

from io import StringIO
from pyinfra.api.operation import add_op
from pyinfra.operations import server, files
from pyinfra.facts.server import Kernel


def add_registry_ops(state, hosts, config, target_hosts=None, task="all"):
    """Deploy Docker Container Registry (registry:2) with auth and storage.

    Args:
        state: pyinfra State object
        hosts: Inventory object
        config: dict mapping hostname → {
            "version": "2.8",
            "listen_port": 5000,
            "storage_path": "/data/registry",
            "storage_backend": "filesystem",  # or s3, gcs, azure
            "auth": {
                "type": "htpasswd",  # or none, token, etc.
                "users": [{"username": "user", "password": "hash"}],
            },
            "tls": {
                "certificate": "/certs/cert.pem",
                "key": "/certs/key.pem",
            },
        }
        target_hosts: list of Host objects to deploy to (default: all)
        task: "registry" or "all" (for compatibility)
    """
    targets = target_hosts if target_hosts else list(hosts)

    for host in targets:
        if host.name not in config:
            continue

        spec = config[host.name]
        os_key = host.get_fact(Kernel)

        version = spec.get("version", "2.8")
        storage_path = spec.get("storage_path", "/data/registry")
        listen_port = spec.get("listen_port", 5000)

        # Create storage directory
        add_op(
            state,
            server.shell,
            name=f"Create registry storage directory on {host.name}",
            commands=[
                f"mkdir -p {storage_path}/data {storage_path}/auth {storage_path}/certs",
                f"chmod -R 755 {storage_path}",
            ],
            host=host,
        )

        # Generate registry config.yml
        config_yml = _generate_registry_config(spec, storage_path)

        add_op(
            state,
            files.put,
            name=f"Deploy registry config on {host.name}",
            src=StringIO(config_yml),
            dest=f"{storage_path}/config.yml",
            user="root",
            group="root",
            mode="0644",
            host=host,
        )

        # Setup authentication if specified
        auth = spec.get("auth", {})
        if auth.get("type") == "htpasswd" and auth.get("users"):
            _setup_htpasswd_auth(state, host, storage_path, auth["users"])

        # Deploy TLS certificates if specified
        tls = spec.get("tls", {})
        if tls.get("certificate") and tls.get("key"):
            _deploy_tls_certs(state, host, storage_path, tls)

        # Generate and deploy docker-compose.yml
        compose_yml = _generate_compose_yml(spec, storage_path, listen_port)

        add_op(
            state,
            files.put,
            name=f"Deploy registry docker-compose.yml on {host.name}",
            src=StringIO(compose_yml),
            dest=f"{storage_path}/docker-compose.yml",
            user="root",
            group="root",
            mode="0644",
            host=host,
        )

        # Start registry container
        add_op(
            state,
            server.shell,
            name=f"Start Docker Registry on {host.name}",
            commands=[
                f"cd {storage_path}",
                f"docker-compose pull",
                f"docker-compose up -d",
                f"docker-compose ps",
            ],
            host=host,
        )

        # Health check
        add_op(
            state,
            server.shell,
            name=f"Registry health check on {host.name}",
            commands=[
                f"sleep 5",
                f"curl -s http://localhost:{listen_port}/v2/ | grep -q '{{}}' && echo 'Registry healthy'",
            ],
            host=host,
        )


def _generate_registry_config(spec, storage_path):
    """Generate registry config.yml."""
    storage_backend = spec.get("storage_backend", "filesystem")

    config_lines = [
        "# Generated by Flamelet",
        "version: 0.1",
        "log:",
        "  level: info",
        "  fields:",
        "    service: registry",
        "storage:",
    ]

    # Storage backend configuration
    if storage_backend == "filesystem":
        config_lines.extend([
            "  filesystem:",
            f"    rootdirectory: {storage_path}/data",
        ])
    elif storage_backend == "s3":
        config_lines.extend([
            "  s3:",
            f"    accesskey: {spec.get('s3_accesskey', '')}",
            f"    secretkey: {spec.get('s3_secretkey', '')}",
            f"    region: {spec.get('s3_region', 'us-east-1')}",
            f"    bucket: {spec.get('s3_bucket', 'registry')}",
        ])

    # Authentication
    auth = spec.get("auth", {})
    if auth.get("type") == "htpasswd":
        config_lines.extend([
            "auth:",
            "  htpasswd:",
            f"    realm: Docker Registry",
            f"    path: {storage_path}/auth/htpasswd",
        ])

    # HTTP/HTTPS
    if spec.get("tls"):
        config_lines.extend([
            "http:",
            f"  addr: 0.0.0.0:5000",
            "  tls:",
            f"    certificate: {storage_path}/certs/cert.pem",
            f"    key: {storage_path}/certs/key.pem",
        ])
    else:
        config_lines.extend([
            "http:",
            f"  addr: 0.0.0.0:5000",
        ])

    return "\n".join(config_lines)


def _setup_htpasswd_auth(state, host, storage_path, users):
    """Setup htpasswd authentication."""
    htpasswd_lines = []
    for user in users:
        username = user.get("username")
        password_hash = user.get("password")  # Should be pre-hashed
        htpasswd_lines.append(f"{username}:{password_hash}")

    htpasswd_content = "\n".join(htpasswd_lines)

    add_op(
        state,
        files.put,
        name=f"Deploy registry htpasswd on {host.name}",
        src=StringIO(htpasswd_content),
        dest=f"{storage_path}/auth/htpasswd",
        user="root",
        group="root",
        mode="0600",
        host=host,
    )


def _deploy_tls_certs(state, host, storage_path, tls):
    """Deploy TLS certificates."""
    cert_content = tls.get("certificate_content")
    key_content = tls.get("key_content")

    if cert_content:
        add_op(
            state,
            files.put,
            name=f"Deploy registry certificate on {host.name}",
            src=StringIO(cert_content),
            dest=f"{storage_path}/certs/cert.pem",
            user="root",
            group="root",
            mode="0644",
            host=host,
        )

    if key_content:
        add_op(
            state,
            files.put,
            name=f"Deploy registry key on {host.name}",
            src=StringIO(key_content),
            dest=f"{storage_path}/certs/key.pem",
            user="root",
            group="root",
            mode="0600",
            host=host,
        )


def _generate_compose_yml(spec, storage_path, listen_port):
    """Generate docker-compose.yml for Registry."""
    version = spec.get("version", "2.8")

    compose_lines = [
        "version: '3'",
        "services:",
        "  registry:",
        f"    image: registry:{version}",
        f"    container_name: registry",
        "    restart: unless-stopped",
        "    ports:",
        f"      - '{listen_port}:5000'",
        "    environment:",
        f"      REGISTRY_CONFIG_PATH: /etc/docker/registry/config.yml",
        "    volumes:",
        f"      - {storage_path}/data:/var/lib/registry",
        f"      - {storage_path}/config.yml:/etc/docker/registry/config.yml:ro",
    ]

    # Add auth volume if using htpasswd
    if spec.get("auth", {}).get("type") == "htpasswd":
        compose_lines.append(f"      - {storage_path}/auth:/auth:ro")

    # Add TLS volumes if configured
    if spec.get("tls"):
        compose_lines.append(f"      - {storage_path}/certs:/certs:ro")

    return "\n".join(compose_lines)
