"""Manage /etc/resolv.conf on FreeBSD systems for persistent DNS configuration."""

from io import StringIO
from pyinfra.api.operation import add_op
from pyinfra.operations import files, server


def add_resolv_conf_ops(state, hosts, config, target_hosts=None, task="all"):
    """Configure /etc/resolv.conf to use local dnsmasq resolver.

    Ensures FreeBSD systems use their local dnsmasq (127.0.0.1) instead of
    Tailscale Magic DNS (100.100.100.100). Also disables Tailscale's automatic
    /etc/resolv.conf management via tailscale set --accept-dns=false.

    Args:
        state: pyinfra State object
        hosts: Inventory object
        config: dict mapping hostname → nameserver config
            {
                "virt.home": {"nameserver": "127.0.0.1"},
                "virt-01.baar": {"nameserver": "127.0.0.1"},
            }
        target_hosts: list of Host objects (default: all)
        task: "resolv-conf" or "all"
    """
    targets = target_hosts if target_hosts else list(hosts)

    for host in targets:
        if host.name not in config:
            continue

        ns_config = config[host.name]
        nameserver = ns_config.get("nameserver", "127.0.0.1")

        # Step 1: Create /etc/resolv.conf with local nameserver (using sudo cat with heredoc)
        add_op(
            state,
            server.shell,
            name=f"Configure /etc/resolv.conf on {host.name}",
            commands=["""sudo sh -c 'cat > /etc/resolv.conf << EOF
# Generated by flamelet - local dnsmasq resolver
nameserver 127.0.0.1
search local
EOF'"""],
            host=host,
        )

        # Step 2: Create rc.d script that disables Tailscale's DNS management
        disable_ts_dns_script = """#!/bin/sh
# Disable Tailscale's automatic /etc/resolv.conf management
# This runs after Tailscale starts but before DNS queries are needed

. /etc/rc.subr

name="tailscale_dns_disable"
rcvar="tailscale_dns_disable_enable"
start_cmd="${name}_start"
stop_cmd="${name}_stop"

tailscale_dns_disable_start() {
    # Wait for tailscaled to be fully up
    sleep 1

    # Disable Tailscale's automatic DNS management (prevent /etc/resolv.conf overwrite)
    if command -v tailscale >/dev/null 2>&1; then
        tailscale set --accept-dns=false 2>/dev/null && \\
            logger "Disabled Tailscale automatic DNS management (accept-dns=false)" || \\
            logger "Warning: Failed to disable Tailscale DNS auto-management"
    fi
}

tailscale_dns_disable_stop() {
    # No cleanup needed on stop
    return 0
}

load_rc_config $name
run_rc_command "$1"
"""

        # Deploy rc.d script with proper permissions using sudo
        add_op(
            state,
            server.shell,
            name=f"Deploy DNS management rc.d script on {host.name}",
            commands=[f"""sudo sh -c 'cat > /etc/rc.d/tailscale_dns_disable << 'SCRIPT'\n{disable_ts_dns_script}SCRIPT\nchmod 755 /etc/rc.d/tailscale_dns_disable'"""],
            host=host,
        )

        # Step 3: Enable the rc.d script in rc.conf
        add_op(
            state,
            server.shell,
            name=f"Enable tailscale_dns_disable in rc.conf on {host.name}",
            commands=["sysrc tailscale_dns_disable_enable=YES"],
            host=host,
        )

        # Step 4: Verify /etc/resolv.conf is correct
        add_op(
            state,
            server.shell,
            name=f"Verify /etc/resolv.conf on {host.name}",
            commands=["cat /etc/resolv.conf"],
            host=host,
        )

        # Step 5: Test DNS resolution to local dnsmasq (if dnsmasq is running)
        add_op(
            state,
            server.shell,
            name=f"Test local DNS resolution on {host.name}",
            commands=["nslookup localhost 127.0.0.1 2>/dev/null | head -3 || echo 'DNS test (expected if dnsmasq not yet running)'"],
            host=host,
        )
