"""Manage /etc/resolv.conf on FreeBSD systems for persistent DNS configuration."""

from pyinfra.api.operation import add_op
from pyinfra.operations import server


def add_resolv_conf_ops(state, hosts, config, target_hosts=None, task="all"):
    """Configure /etc/resolv.conf to use the given nameserver (own dnsmasq, or
    another host's, if this host doesn't run its own resolver).

    Ensures FreeBSD systems use the configured nameserver instead of
    Tailscale Magic DNS (100.100.100.100). Also disables Tailscale's automatic
    /etc/resolv.conf management via tailscale set --accept-dns=false.

    Args:
        state: pyinfra State object
        hosts: Inventory object
        config: dict mapping hostname → nameserver config
            {
                "virt.london": {"nameserver": "127.0.0.1"},
                "virt-01.newyork": {"nameserver": "127.0.0.1"},
            }
        target_hosts: list of Host objects (default: all)
        task: "resolv-conf" or "all"
    """
    targets = target_hosts if target_hosts else list(hosts)

    for host in targets:
        if host.name not in config:
            continue

        ns_config = config[host.name]
        nameserver = ns_config.get("nameserver", "127.0.0.1")

        # Step 1: Create /etc/resolv.conf with configured nameserver (using sudo cat with heredoc)
        add_op(
            state,
            server.shell,
            name=f"Configure /etc/resolv.conf on {host.name}",
            commands=[
                f"""sudo sh -c 'cat > /etc/resolv.conf << EOF
# Generated by flamelet - resolver
nameserver {nameserver}
search local
EOF'"""
            ],
            host=host,
        )

        # Step 2: Create rc.d script that disables Tailscale's DNS management
        disable_ts_dns_script = """#!/bin/sh
# Disable Tailscale's automatic /etc/resolv.conf management
# This runs after Tailscale starts but before DNS queries are needed

. /etc/rc.subr

name="tailscale_dns_disable"
rcvar="tailscale_dns_disable_enable"
start_cmd="${name}_start"
stop_cmd="${name}_stop"

tailscale_dns_disable_start() {
    # Wait for tailscaled to be fully up
    sleep 1

    # Disable Tailscale's automatic DNS management (prevent /etc/resolv.conf overwrite)
    if command -v tailscale >/dev/null 2>&1; then
        tailscale set --accept-dns=false 2>/dev/null && \\
            logger "Disabled Tailscale automatic DNS management (accept-dns=false)" || \\
            logger "Warning: Failed to disable Tailscale DNS auto-management"
    fi
}

tailscale_dns_disable_stop() {
    # No cleanup needed on stop
    return 0
}

load_rc_config $name
run_rc_command "$1"
"""

        # Deploy rc.d script with proper permissions using sudo.
        # NOTE: previously this used `sudo sh -c 'cat > ... << 'SCRIPT' ...'` -
        # nesting a single-quoted heredoc delimiter inside an outer single-quoted
        # sh -c string breaks in POSIX shell (no quote nesting), which closed the
        # outer string early and produced "Usage: sh [fast|force|...]" failures.
        # `sudo tee` avoids the outer single-quote wrapper entirely.
        add_op(
            state,
            server.shell,
            name=f"Deploy DNS management rc.d script on {host.name}",
            commands=[
                f"""sudo tee /etc/rc.d/tailscale_dns_disable > /dev/null << 'SCRIPT'\n{disable_ts_dns_script}SCRIPT""",
                "sudo chmod 755 /etc/rc.d/tailscale_dns_disable",
            ],
            host=host,
        )

        # Step 3: Enable the rc.d script in rc.conf
        add_op(
            state,
            server.shell,
            name=f"Enable tailscale_dns_disable in rc.conf on {host.name}",
            commands=["sysrc tailscale_dns_disable_enable=YES"],
            host=host,
        )

        # Step 4: Verify /etc/resolv.conf is correct
        add_op(
            state,
            server.shell,
            name=f"Verify /etc/resolv.conf on {host.name}",
            commands=["cat /etc/resolv.conf"],
            host=host,
        )

        # Step 5: Test DNS resolution to the configured nameserver (if it's up)
        add_op(
            state,
            server.shell,
            name=f"Test DNS resolution on {host.name}",
            commands=[
                f"nslookup localhost {nameserver} 2>/dev/null | head -3 || echo 'DNS test (expected if {nameserver} not yet reachable)'"
            ],
            host=host,
        )
