"""Tests for the dnsmasq resolv.conf handling.

The operation these cover used to begin with

    echo 'nameserver 127.0.0.1' > /etc/resolv.conf

which truncated the file. That threw away `search` domains and every other
nameserver, and on a host whose resolv.conf is owned by another tool (a VPN
mesh, resolvconf, NetworkManager, systemd-resolved) it also fought the owner for
control of the file. The mesh case is the one that actually hurts: the mesh
resolver is usually the only thing that can resolve the mesh's own names, so
dropping it costs you the names you reached the host by.

These tests pin the three behaviours that fix depends on, because all three are
easy to regress with a one-line edit and none of them fail loudly in a dry run.
"""

import subprocess
from pathlib import Path

from core.operations.dnsmasq import _resolver_commands


def _run(target: Path) -> str:
    """Execute the generated snippet against a real file and return its output."""
    (command,) = _resolver_commands(str(target))
    return subprocess.run(["sh", "-c", command], capture_output=True, text=True, check=True).stdout


class TestResolverCommands:
    def test_leaves_externally_managed_file_untouched(self, tmp_path):
        """A file another tool owns must not be rewritten at all."""
        for marker in (
            "# Generated by NetBird",
            "# Generated by resolvconf",
            "# This file is managed by systemd-resolved",
            "# Do not edit",
        ):
            resolv = tmp_path / "resolv.conf"
            original = f"{marker}\n\nsearch example.com\nnameserver 192.0.2.53\n"
            resolv.write_text(original)

            _run(resolv)

            assert resolv.read_text() == original, f"clobbered a file marked {marker!r}"

    def test_preserves_search_domains_and_existing_nameservers(self, tmp_path):
        """The original truncation bug: everything below line one was discarded."""
        resolv = tmp_path / "resolv.conf"
        resolv.write_text("search example.com\nnameserver 192.0.2.53\nnameserver 1.1.1.1\n")

        _run(resolv)

        lines = resolv.read_text().splitlines()
        assert lines[0] == "nameserver 127.0.0.1", "local resolver must come FIRST"
        assert "search example.com" in lines, "search domains were dropped"
        assert "nameserver 192.0.2.53" in lines, "an existing nameserver was dropped"
        assert "nameserver 1.1.1.1" in lines

    def test_is_idempotent(self, tmp_path):
        """Re-running must not stack duplicate entries or leave scratch files."""
        resolv = tmp_path / "resolv.conf"
        resolv.write_text("search example.com\nnameserver 192.0.2.53\n")

        _run(resolv)
        after_first = resolv.read_text()
        _run(resolv)

        assert resolv.read_text() == after_first
        assert after_first.count("nameserver 127.0.0.1") == 1
        assert list(tmp_path.iterdir()) == [resolv], "left a scratch file behind"

    def test_carries_no_hardcoded_deployment_address(self):
        """The dead-code guard appended one deployment's literal address.

        It grepped resolv.conf *after* the redirect on the preceding line had
        already emptied it, so the guard never matched and the address was
        appended unconditionally -- to every tenant.
        """
        (command,) = _resolver_commands()

        assert "10.10.0.1" not in command
